services:
  - type: web
    name: pmss-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: SUPER_ADMIN_EMAIL
        value: admin@helvino.org
      - key: SUPER_ADMIN_PASSWORD
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
